# Site settings
title: Documentation
project_title: UC Libraries Digital Collections
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: June 9, 2014
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://localhost:4000"
username: ucldc

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
