# Site settings
title: Documentation
project_title: UC Libraries Digital Collection
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: November 4, 2015
email: ucldc@ucop.edu
description: ""
# baseurl: ""
baseurl: "/ucldc-docs"
# url: "http://0.0.0.0:4000"
url: "http://ucldc.github.io"
username: ucldc

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

collections:
  docs:
    output: true
    permalink: /docs/:path/
  dams:
    output: true
    permalink: /docs/dams/:path/
  registry:
    output: true
    permalink: /docs/registry/:path/
  technical:
    output: true
    permalink: /docs/technical/:path/
    
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
  - scope:
      path: ""
      type: dams
    values:
      layout: doc
  - scope:
      path: ""
      type: registry
    values:
      layout: doc
  - scope:
      path: ""
      type: technical
    values:
      layout: doc