# Site settings
title: Documentation
project_title: UC Libraries Digital Collection
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: September 3, 2015
email: ucldc@ucop.edu
description: ""
baseurl: "/ucldc-docs"
url: "http://ucldc.github.io"
username: ucldc

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
