# Site settings
title: Documentation
project_title: UC Libraries Digital Collection
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: November 4, 2015
email: ucldc@ucop.edu
description: ""
# baseurl: ""
baseurl: "/ucldc-docs"
# url: "http://0.0.0.0:4000"
url: "http://ucldc.github.io"
username: ucldc

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

collections:
  docs:
    output: true
    permalink: /docs/:path/
  dams:
    output: true
    permalink: /docs/dams/:path/
  registry:
    output: true
    permalink: /docs/registry/:path/
  technical-docs:
    output: true
    permalink: /docs/technical-docs/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
  - scope:
      path: ""
      type: dams
    values:
      layout: dams-doc
      breadcrumbs: DAMS User Guide
  - scope:
      path: ""
      type: registry
    values:
      layout: registry-doc
      breadcrumbs: Calisphere Admin Guide
  - scope:
      path: ""
      type: technical-docs
    values:
      layout: technical-doc
      breadcrumbs: Common Index API