# Site settings
title: Documentation
project_title: UC Libraries Digital Collections
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: June 9, 2014
email: your-email@domain.com
description: ""
baseurl: "/ucldc-docs"
url: "http://ucldc.github.io"
username: ucldc

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
