# Site settings
title: Documentation
project_title: UC Libraries Digital Collections
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: June 5, 2014
email: your-email@domain.com
description: ""
baseurl: "/ucldc"
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
username: ucldc
